// export { default as Sidebar } from './sidebar/vertical.vue'
// export { default as Navbar } from './navbar'
// export { default as AppMain } from './app-main'
// export { default as Footer } from './footer'
// export { default as Settings } from './settings'
export { default as Sidebar } from './sidebar/vertical.vue'
export { default as Navbar } from './navbar/index.vue'
export { default as AppMain } from './app-main/index.vue'
export { default as Footer } from './footer/index.vue'
export { default as Settings } from './settings/index.vue'
